name: flyer_chat_video_message
version: 0.0.15
description: >
  Video message package for Flutter chat apps, complementing flutter_chat_ui. #chat #ui
homepage: https://flyer.chat
repository: https://github.com/flyerhq/flutter_chat_ui

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_chat_core: ^2.7.1
  media_kit: ^1.2.6
  media_kit_libs_video: ^1.0.7
  media_kit_video: ^2.0.1
  thumbhash: ^0.1.0+1
  video_thumbnail: ^0.5.6

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
